---
defaults:
  updatinator_container: &updatinator_container
    working_directory: /updatinator

executors:
  vault-image:
    docker:
      - image: docker.io/hashicorp/vault:1.15

version: 2
jobs:
  vault-login:
    executor: vault-image
    steps:
      - checkout
      - run:
          name: "Vault Login"
          command: |
            export VAULT_ADDR="https://api.vault-production.pantheon.io:8200"

            VAULT_TOKEN=$(vault write auth/jwt-circleci/login role=circleci -format=json role=circleci jwt=$CIRCLE_OIDC_TOKEN | jq -r '.auth.client_token')
            if [ -z "$VAULT_TOKEN" ]; then
              echo "Failed to get Vault token"
              exit 1
            fi
            echo "export VAULT_TOKEN=$VAULT_TOKEN" >> $BASH_ENV
            echo "export PRODUCTION_VAULT_TOKEN=$VAULT_TOKEN" >> $BASH_ENV
  test:
    <<: *updatinator_container
    docker:
      - image: quay.io/pantheon-public/docker-updatinator:3.x
      - image: cimg/mysql:5.7.36
    steps:
      - checkout
      - run:
          name: "Install Composer Dependencies"
          command: composer install
      - run:
          name: "Setup Git Config"
          command: |
            git config --global user.email "bot@getpantheon.com"
            git config --global user.name "Pantheon Automation"
      - run:
          name: "Test Update Tool"
          command: ./update-tool whoami
      - run:
          name: "Test Vault"
          command: which vault
      - run:
          name: "Build Update Tool"
          command: composer phar:build
      - persist_to_workspace:
          root: /updatinator
          paths:
            - update-tool.phar
      - run: composer test
  publish_phar:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$CIRCLE_TAG
            which pvault
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/update-tool.phar

workflows:
  version: 2
  push:
    jobs:
      - vault-login:
        - context:
            - gcp-credentials-ar-ci
      - test:
          context:
            - gcp-credentials-ar-ci
          filters:
            tags:
              only: /.*/
          requires:
            - vault-login
      - publish_phar:
          context:
            - gcp-credentials-ar-ci
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
