---
defaults:
  updatinator_container: &updatinator_container
    working_directory: /updatinator

version: 2
jobs:
  test:
    <<: *updatinator_container
    docker:
      - image: quay.io/pantheon-public/docker-updatinator:1.x
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: git config --global user.email "bot@getpantheon.com"
      - run: git config --global user.name "Pantheon Automation"
      - run: ./updatinate whoami
      - run: composer test

workflows:
  version: 2
  push:
    jobs:
      - test
