---
defaults:
  updatinator_container: &updatinator_container
    docker:
      - image: quay.io/pantheon-public/docker-updatinator:1.x
    working_directory: /updatinator

version: 2
jobs:
  test:
    <<: *updatinator_container
    steps:
      - checkout
      - run: composer install --prefer-dist --no-interaction
workflows:
  version: 2
  push:
    jobs:
      - test
