---
defaults:
  updatinator_container: &updatinator_container
    working_directory: /updatinator

version: 2

jobs:
  vault-login:
    docker:
      - image: docker.io/hashicorp/vault:1.15
    steps:
      - checkout
      - run:
          name: "Install jq and curl"
          command: |
            apk add jq
            apk add curl
      - run:
          name: "Vault Login"
          command: |
            export VAULT_ADDR="https://api.vault-production.pantheon.io:8200"
            export VAULT_CACERT=pantheon-ca-all.crt
            curl -fsSL https://storage.googleapis.com/pantheon-ca-certs/ca.crt > $VAULT_CACERT
            echo "" >> $VAULT_CACERT
            curl -fsSL https://storage.googleapis.com/pantheon-sandbox-ca-certs/ca.crt >> $VAULT_CACERT
            VAULT_TOKEN=$(vault write auth/jwt-circleci/login -format=json role=circleci jwt=$CIRCLE_OIDC_TOKEN | jq -r '.auth.client_token')
            if [ -z "$VAULT_TOKEN" ]; then
              echo "Failed to get Vault token"
              exit 1
            fi
            # echo "export VAULT_TOKEN=$VAULT_TOKEN" >> $BASH_ENV
            # echo "export PRODUCTION_VAULT_TOKEN=$VAULT_TOKEN" >> $BASH_ENV
            touch secrets-env && chmod 600 secrets-env
            echo export "VAULT_TOKEN=\"${VAULT_TOKEN}\"" >> secrets-env
            echo export "VAULT_ADDR=\"${VAULT_ADDR}\"" >> secrets-env
            echo export "VAULT_CACERT=\"${VAULT_CACERT}\"" >> secrets-env
      - run:
          name: "Export GitHub Token from Vault"
          command: |
            # Make sure we have vault.
            which vault
            if [ $? -ne 0 ]; then
              echo "Vault not found...weird... 🤔"
              exit 1
            fi
            # Make sure we have secrets-env.
            if [ ! -f secrets-env ]; then
              echo "Could not find secrets-env! 😱 Exiting..."
              exit 1
            else
              . secrets-env
            fi
            CIRCLE_GH_TOKEN=$(vault read -field=token secret/github/access-tokens/pantheon-ci-bot)
            if [ -z "$CIRCLE_GH_TOKEN" ]; then
              echo "Failed to get GitHub token"
              exit 1
            fi
            export $CIRCLE_GH_TOKEN >> $BASH_ENV
  test:
    <<: *updatinator_container
    docker:
      - image: quay.io/pantheon-public/docker-updatinator:3.x
      - image: cimg/mysql:5.7.36
    steps:
      - checkout
      - run:
          name: "Install Composer Dependencies"
          command: composer install
      - run:
          name: "Setup Git Config"
          command: |
            git config --global user.email "bot@getpantheon.com"
            git config --global user.name "Pantheon Automation"
      - run:
          name: "Test Update Tool"
          command: ./update-tool whoami
      - run:
          name: "Test Token from Vault"
          command: |
            if [ -z "$CIRCLE_GH_TOKEN" ]; then
              echo "Could not find GH token! 😱 Exiting..."
              exit 1
            fi
      - run:
          name: "Build Update Tool"
          command: composer phar:build
      - persist_to_workspace:
          root: /updatinator
          paths:
            - update-tool.phar
      - run: composer test
  publish_phar:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$CIRCLE_TAG
            if [ -z "$CIRCLE_GH_TOKEN" ]; then
              echo "Could not find GH token! 😱 Exiting..."
              exit 1
            fi
            ghr -t ${CIRCLE_GH_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/update-tool.phar

workflows:
  version: 2
  push:
    jobs:
      - vault-login
      - test:
          context:
            - gcp-credentials-ar-ci
          filters:
            tags:
              only: /.*/
          requires:
            - vault-login
      - publish_phar:
          context:
            - gcp-credentials-ar-ci
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
